use constants::*;
use self::LRType::*;

pub struct CDF {
    intra_frame_y_mode: [[[i32; INTRA_MODES+1]; INTRA_MODE_CONTEXTS]; INTRA_MODE_CONTEXTS],
    y_mode: [[i32; INTRA_MODES+1]; BLOCK_SIZE_GROUPS],
    uv_mode_cfl_not_allowed: [[i32; UV_INTRA_MODES_CFL_NOT_ALLOWED+1]; INTRA_MODES],
    uv_mode_cfl_allowed: [[i32; UV_INTRA_MODES_CFL_ALLOWED+1]; INTRA_MODES],
    angle_delta: [[i32; (2*MAX_ANGLE_DELTA+1)+1]; DIRECTIONAL_MODES],
    intrabc: [i32; 2+1],
    partition_w8: [[i32; 5]; PARTITION_CONTEXTS],
    partition_w16: [[i32; 11]; PARTITION_CONTEXTS],
    partition_w32: [[i32; 11]; PARTITION_CONTEXTS],
    partition_w64: [[i32; 11]; PARTITION_CONTEXTS],
    partition_w128: [[i32; 9]; PARTITION_CONTEXTS],
    tx_8x8: [[i32; MAX_TX_DEPTH+1]; TX_SIZE_CONTEXTS],
    tx_16x16: [[i32; MAX_TX_DEPTH+2]; TX_SIZE_CONTEXTS],
    tx_32x32: [[i32; MAX_TX_DEPTH+2]; TX_SIZE_CONTEXTS],
    tx_64x64: [[i32; MAX_TX_DEPTH+2]; TX_SIZE_CONTEXTS],
    txfm_split: [[i32; 3]; TXFM_PARTITION_CONTEXTS],
    filter_intra_mode: [i32; 6],
    filter_intra: [[i32; 3]; BLOCK_SIZES],
    segment_id: [[i32; MAX_SEGMENTS+1]; SEGMENT_ID_CONTEXTS],
    segment_id_predicted: [[i32; 3]; SEGMENT_ID_PREDICTED_CONTEXTS],
    mv_class0_hp: [i32; 3],
    mv_hp: [i32; 3],
    mv_sign: [i32; 3],
    mv_bit: [[i32; 3]; MV_OFFSET_BITS],
    mv_class0_bit: [i32; 3],
    new_mv: [[i32; 3]; NEW_MV_CONTEXTS],
    zero_mv: [[i32; 3]; ZERO_MV_CONTEXTS],
    ref_mv: [[i32; 3]; REF_MV_CONTEXTS],
    drl_mode: [[i32; 3]; DRL_MODE_CONTEXTS],
    is_inter: [[i32; 3]; IS_INTER_CONTEXTS],
    comp_mode: [[i32; 3]; COMP_INTER_CONTEXTS],
    skip_mode: [[i32; 3]; SKIP_MODE_CONTEXTS],
    skip: [[i32; 3]; SKIP_CONTEXTS],
    comp_ref: [[[i32; 3]; FWD_REFS-1]; REF_CONTEXTS],
    comp_bwd_ref: [[[i32; 3]; BWD_REFS-1]; REF_CONTEXTS],
    comp_single_ref: [[[i32; 3]; SINGLE_REFS-1]; REF_CONTEXTS],
    compound_mode: [[i32; COMPOUND_MODES+1]; COMPOUND_MODE_CONTEXTS],
    interp_filter: [[i32; INTERP_FILTERS+1]; INTERP_FILTER_CONTEXTS],
    motion_mode: [[i32; MOTION_MODES+1]; BLOCK_SIZES],
    mv_joint: [i32; MV_JOINTS+1],
    mv_class: [[i32; MV_CLASSES+1]; 2],
    mv_class0_fr: [[[i32; MV_JOINTS+1]; CLASS0_SIZE]; 2],
    mv_fr: [[i32; MV_JOINTS+1]; 2],
    palette_y_size: [[i32; PALETTE_SIZES+1]; PALETTE_BLOCK_SIZE_CONTEXTS],
    palette_size_2_y_color: [[i32; 3]; PALETTE_COLOR_CONTEXTS],
    palette_size_3_y_color: [[i32; 4]; PALETTE_COLOR_CONTEXTS],
    palette_size_4_y_color: [[i32; 5]; PALETTE_COLOR_CONTEXTS],
    palette_size_5_y_color: [[i32; 6]; PALETTE_COLOR_CONTEXTS],
    palette_size_6_y_color: [[i32; 7]; PALETTE_COLOR_CONTEXTS],
    palette_size_7_y_color: [[i32; 8]; PALETTE_COLOR_CONTEXTS],
    palette_size_8_y_color: [[i32; 9]; PALETTE_COLOR_CONTEXTS],
    palette_size_2_uv_color: [[i32; 3]; PALETTE_COLOR_CONTEXTS],
    palette_size_3_uv_color: [[i32; 4]; PALETTE_COLOR_CONTEXTS],
    palette_size_4_uv_color: [[i32; 5]; PALETTE_COLOR_CONTEXTS],
    palette_size_5_uv_color: [[i32; 6]; PALETTE_COLOR_CONTEXTS],
    palette_size_6_uv_color: [[i32; 7]; PALETTE_COLOR_CONTEXTS],
    palette_size_7_uv_color: [[i32; 8]; PALETTE_COLOR_CONTEXTS],
    palette_size_8_uv_color: [[i32; 9]; PALETTE_COLOR_CONTEXTS],
    palette_y_mode: [[[i32; 3]; PALETTE_Y_MODE_CONTEXTS]; PALETTE_BLOCK_SIZE_CONTEXTS],
    palette_uv_mode: [[i32; 3]; PALETTE_UV_MODE_CONTEXTS],
    delta_q: [i32; DELTA_Q_SMALL+2],
    delta_lf: [i32; DELTA_LF_SMALL+2],
    intra_tx_type_set1: [[[i32; 8]; INTRA_MODES]; 4],
    intra_tx_type_set2: [[[i32; 6]; INTRA_MODES]; 4],
    inter_tx_type_set1: [[i32; 17]; 4],
    inter_tx_type_set2: [[i32; 13]; 4],
    inter_tx_type_set3: [[i32; 3]; 4],
    compound_idx: [[i32; 3]; COMPOUND_IDX_CONTEXTS],
    comp_group_idx: [[i32; 3]; COMP_GROUP_IDX_CONTEXTS],
    compound_type: [[i32; COMPOUND_TYPES+1]; BLOCK_SIZES],
    inter_intra: [[i32; 3]; BLOCK_SIZE_GROUPS],
    inter_intra_mode: [[i32; INTERINTRA_MODES+1]; BLOCK_SIZE_GROUPS],
    wedge_index: [[i32; 16+1]; BLOCK_SIZES],
    wedge_inter_intra: [[i32; 3]; BLOCK_SIZES],
    use_obmc: [[i32; 3]; BLOCK_SIZES],
    comp_ref_type: [[i32; 3]; COMP_REF_TYPE_CONTEXTS],
    uni_comp_ref: [[[i32; 3]; UNIDIR_COMP_REFS-1]; REF_CONTEXTS],
    cfl_sign: [i32; CFL_JOINT_SIGNS+1],
    cfl_alpha: [[i32; CFL_ALPHABET_SIZE+1]; CFL_ALPHA_CONTEXTS],
    use_wiener: [i32; 2+1],
    use_sgrproj: [i32; 2+1],
    restoration_type: [i32; RESTORE_SWITCHABLE as usize +1],
    txb_skip: [[[[i32; 3]; TXB_SKIP_CONTEXTS]; TX_SIZES]; COEFF_CDF_Q_CTXS],
    eob_pt_16: [[[[i32; 6]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_32: [[[[i32; 7]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_64: [[[[i32; 8]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_128: [[[[i32; 9]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_256: [[[[i32; 10]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_512: [[[[i32; 11]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_pt_1024: [[[[i32; 12]; 2]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    eob_extra: [[[[[i32; 3]; EOB_COEF_CONTEXTS]; PLANE_TYPES]; TX_SIZES]; COEFF_CDF_Q_CTXS],
    dc_sign: [[[[i32; 3]; DC_SIGN_CONTEXTS]; PLANE_TYPES]; COEFF_CDF_Q_CTXS],
    coeff_base_eob: [[[[[i32; 4]; SIG_COEF_CONTEXTS_EOB]; PLANE_TYPES]; TX_SIZES]; COEFF_CDF_Q_CTXS],
    coeff_base: [[[[[i32; 5]; SIG_COEF_CONTEXTS]; PLANE_TYPES]; TX_SIZES]; COEFF_CDF_Q_CTXS],
    coeff_br: [[[[[i32; BR_CDF_SIZE+1]; LEVEL_CONTEXTS]; PLANE_TYPES]; TX_SIZES]; COEFF_CDF_Q_CTXS],
}