#![allow(non_camel_case_types)]
#![allow(dead_code)]

pub enum ColorPrimaries {
    CP_BT_709 = 1,
    CP_UNSPECIFIED = 2,
    CP_BT_470_M = 4,
    CP_BT_470_B_G = 5,
    CP_BT_601 = 6,
    CP_SMPTE_240 = 7,
    CP_GENERIC_FILM = 8,
    CP_BT_2020 = 9,
    CP_XYZ = 10,
    CP_SMPTE_431 = 11,
    CP_SMPTE_432 = 12,
    CP_EBU_3213 = 22,
}

pub enum TransferCharacteristics {
    TC_RESERVED_0 = 0,
    TC_BT_709 = 1,
    TC_UNSPECIFIED = 2,
    TC_RESERVED_3 = 3,
    TC_BT_470_M = 4,
    TC_BT_470_B_G = 5,
    TC_BT_601 = 6,
    TC_SMPTE_240 = 7,
    TC_LINEAR = 8,
    TC_LOG_100 = 9,
    TC_LOG_100_SQRT10 = 10,
    TC_IEC_61966 = 11,
    TC_BT_1361 = 12,
    TC_SRGB = 13,
    TC_BT_2020_10_BIT = 14,
    TC_BT_2020_12_BIT = 15,
    TC_SMPTE_2084 = 16,
    TC_SMPTE_428 = 17,
    TC_HLG = 18,
}

pub enum MatrixCoefficients {
    MC_IDENTITY = 0,
    MC_BT_709 = 1,
    MC_UNSPECIFIED = 2,
    MC_RESERVED_3 = 3,
    MC_FCC = 4,
    MC_BT_470_B_G = 5,
    MC_BT_601 = 6,
    MC_SMPTE_240 = 7,
    MC_SMPTE_YCGCO = 8,
    MC_BT_2020_NCL = 9,
    MC_BT_2020_CL = 10,
    MC_SMPTE_2085 = 11,
    MC_CHROMAT_NCL = 12,
    MC_CHROMAT_CL = 13,
    MC_ICTCP = 14,
}

pub enum FrameType {
    KEY_FRAME = 0,
    INTER_FRAME = 1,
    INTRA_ONLY_FRAME = 2,
    SWITCH_FRAME = 3,
}

pub enum LRType {
    RESTORE_NONE = 0,
    RESTORE_SWITCHABLE = 1,
    RESTORE_WIENER = 2,
    RESTORE_SGRPROJ = 3,
}

pub const REFS_PER_FRAME: usize = 7;
pub const TOTAL_REFS_PER_FRAME: usize = 8;
pub const BLOCK_SIZE_GROUPS: usize = 4;
pub const BLOCK_SIZES: usize = 22;
pub const BLOCK_INVALID: usize = 22;
pub const MAX_SB_SIZE: usize = 128;
pub const MI_SIZE: usize = 4;
pub const MI_SIZE_LOG2: usize = 2;
pub const MAX_TILE_WIDTH: usize = 4096;
pub const MAX_TILE_AREA: usize = 4096 * 2304;
pub const MAX_TILE_ROWS: usize = 64;
pub const MAX_TILE_COLS: usize = 64;
pub const INTRABC_DELAY_PIXELS: usize = 256;
pub const INTRABC_DELAY_SB64: usize = 4;
pub const NUM_REF_FRAMES: usize = 8;
pub const IS_INTER_CONTEXTS: usize = 4;
pub const REF_CONTEXTS: usize = 3;
pub const MAX_SEGMENTS	: usize = 8;
pub const SEGMENT_ID_CONTEXTS: usize = 3;
pub const SEG_LVL_ALT_Q: usize = 0;
pub const SEG_LVL_ALT_LF_Y_V: usize = 1;
pub const SEG_LVL_REF_FRAME: usize = 5;
pub const SEG_LVL_SKIP: usize = 6;
pub const SEG_LVL_GLOBALMV: usize = 7;
pub const SEG_LVL_MAX: usize = 7;
pub const PLANE_TYPES: usize = 2;
pub const TX_SIZE_CONTEXTS: usize = 3;
pub const INTERP_FILTERS: usize = 3;
pub const INTERP_FILTER_CONTEXTS: usize = 16;
pub const SKIP_MODE_CONTEXTS: usize = 3;
pub const SKIP_CONTEXTS: usize = 3;
pub const PARTITION_CONTEXTS: usize = 4;
pub const TX_SIZES: usize = 5;
pub const TX_SIZES_ALL: usize = 19;
pub const TX_MODES: usize = 3;
pub const DCT_DCT: usize = 0;
pub const ADST_DCT: usize = 1;
pub const DCT_ADST: usize = 2;
pub const ADST_ADST: usize = 3;
pub const FLIPADST_DCT: usize = 4;
pub const DCT_FLIPADST: usize = 5;
pub const FLIPADST_FLIPADST: usize = 6;
pub const ADST_FLIPADST: usize = 7;
pub const FLIPADST_ADST: usize = 8;
pub const IDTX: usize = 9;
pub const V_DCT: usize = 10;
pub const H_DCT: usize = 11;
pub const V_ADST: usize = 12;
pub const H_ADST: usize = 13;
pub const V_FLIPADST: usize = 14;
pub const H_FLIPADST: usize = 15;
pub const TX_TYPES: usize = 16;
pub const MB_MODE_COUNT: usize = 17;
pub const INTRA_MODES: usize = 13;
pub const UV_INTRA_MODES_CFL_NOT_ALLOWED: usize = 13;
pub const UV_INTRA_MODES_CFL_ALLOWED: usize = 14;
pub const COMPOUND_MODES: usize = 8;
pub const COMPOUND_MODE_CONTEXTS: usize = 8;
pub const COMP_NEWMV_CTXS: usize = 5;
pub const NEW_MV_CONTEXTS: usize = 6;
pub const ZERO_MV_CONTEXTS: usize = 2;
pub const REF_MV_CONTEXTS: usize = 6;
pub const DRL_MODE_CONTEXTS: usize = 3;
pub const MV_CONTEXTS: usize = 2;
pub const MV_INTRABC_CONTEXT: usize = 1;
pub const MV_JOINTS: usize = 4;
pub const MV_CLASSES: usize = 11;
pub const CLASS0_SIZE: usize = 2;
pub const MV_OFFSET_BITS: usize = 10;
pub const MAX_LOOP_FILTER: usize = 63;
pub const REF_SCALE_SHIFT: usize = 14;
pub const SUBPEL_BITS: usize = 4;
pub const SUBPEL_MASK: usize = 15;
pub const SCALE_SUBPEL_BITS: usize = 10;
pub const MV_BORDER: usize = 128;
pub const PALETTE_COLOR_CONTEXTS: usize = 5;
pub const PALETTE_MAX_COLOR_CONTEXT_HASH: usize = 8;
pub const PALETTE_BLOCK_SIZE_CONTEXTS: usize = 7;
pub const PALETTE_Y_MODE_CONTEXTS: usize = 3;
pub const PALETTE_UV_MODE_CONTEXTS: usize = 2;
pub const PALETTE_SIZES: usize = 7;
pub const PALETTE_COLORS: usize = 8;
pub const PALETTE_NUM_NEIGHBORS: usize = 3;
pub const DELTA_Q_SMALL: usize = 3;
pub const DELTA_LF_SMALL: usize = 3;
pub const QM_TOTAL_SIZE: usize = 3344;
pub const MAX_ANGLE_DELTA: usize = 3;
pub const DIRECTIONAL_MODES: usize = 8;
pub const ANGLE_STEP: usize = 3;
pub const TX_SET_TYPES_INTRA: usize = 3;
pub const TX_SET_TYPES_INTER: usize = 4;
pub const WARPEDMODEL_PREC_BITS: usize = 16;
pub const IDENTITY: usize = 0;
pub const TRANSLATION: usize = 1;
pub const ROTZOOM: usize = 2;
pub const AFFINE: usize = 3;
pub const GM_ABS_TRANS_BITS: usize = 12;
pub const GM_ABS_TRANS_ONLY_BITS: usize = 9;
pub const GM_ABS_ALPHA_BITS: usize = 12;
pub const DIV_LUT_PREC_BITS: usize = 14;
pub const DIV_LUT_BITS: usize = 8;
pub const DIV_LUT_NUM: usize = 257;
pub const MOTION_MODES: usize = 3;
pub const SIMPLE: usize = 0;
pub const OBMC: usize = 1;
pub const LOCALWARP: usize = 2;
pub const LEAST_SQUARES_SAMPLES_MAX: usize = 8;
pub const LS_MV_MAX: usize = 256;
pub const WARPEDMODEL_TRANS_CLAMP: usize = 1<<23;
pub const WARPEDMODEL_NONDIAGAFFINE_CLAMP: usize = 1<<13;
pub const WARPEDPIXEL_PREC_SHIFTS: usize = 1<<6;
pub const WARPEDDIFF_PREC_BITS: usize = 10;
pub const GM_ALPHA_PREC_BITS: usize = 15;
pub const GM_TRANS_PREC_BITS: usize = 6;
pub const GM_TRANS_ONLY_PREC_BITS: usize = 3;
pub const INTERINTRA_MODES: usize = 4;
pub const MASK_MASTER_SIZE: usize = 64;
pub const SEGMENT_ID_PREDICTED_CONTEXTS: usize = 3;
pub const FWD_REFS: usize = 4;
pub const BWD_REFS: usize = 3;
pub const SINGLE_REFS: usize = 7;
pub const UNIDIR_COMP_REFS: usize = 4;
pub const COMPOUND_TYPES: usize = 2;
pub const CFL_JOINT_SIGNS: usize = 8;
pub const CFL_ALPHABET_SIZE: usize = 16;
pub const COMP_INTER_CONTEXTS: usize = 5;
pub const COMP_REF_TYPE_CONTEXTS: usize = 5;
pub const CFL_ALPHA_CONTEXTS: usize = 6;
pub const INTRA_MODE_CONTEXTS: usize = 5;
pub const COMP_GROUP_IDX_CONTEXTS: usize = 6;
pub const COMPOUND_IDX_CONTEXTS: usize = 6;
pub const INTRA_EDGE_KERNELS: usize = 3;
pub const INTRA_EDGE_TAPS: usize = 5;
pub const FRAME_LF_COUNT: usize = 4;
pub const MAX_VARTX_DEPTH: usize = 2;
pub const TXFM_PARTITION_CONTEXTS: usize = 21;
pub const REF_CAT_LEVEL: usize = 640;
pub const MAX_REF_MV_STACK_SIZE: usize = 8;
pub const MFMV_STACK_SIZE: usize = 3;
pub const MAX_TX_DEPTH: usize = 2;
pub const WEDGE_TYPES: usize = 16;
pub const FILTER_BITS: usize = 7;
pub const WIENER_COEFFS: usize = 3;
pub const SGRPROJ_PARAMS_BITS: usize = 4;
pub const SGRPROJ_PRJ_SUBEXP_K: usize = 4;
pub const SGRPROJ_PRJ_BITS: usize = 7;
pub const SGRPROJ_RST_BITS: usize = 4;
pub const SGRPROJ_MTABLE_BITS: usize = 20;
pub const SGRPROJ_RECIP_BITS: usize = 12;
pub const SGRPROJ_SGR_BITS: usize = 8;
pub const EC_PROB_SHIFT: usize = 6;
pub const EC_MIN_PROB: usize = 4;
pub const SELECT_SCREEN_CONTENT_TOOLS: usize = 2;
pub const SELECT_INTEGER_MV: usize = 2;
pub const RESTORATION_TILESIZE_MAX: usize = 256;
pub const MAX_FRAME_DISTANCE: usize = 31;
pub const MAX_OFFSET_WIDTH: usize = 8;
pub const MAX_OFFSET_HEIGHT: usize = 0;
pub const WARP_PARAM_REDUCE_BITS: usize = 6;
pub const NUM_BASE_LEVELS: usize = 2;
pub const COEFF_BASE_RANGE: usize = 12;
pub const BR_CDF_SIZE: usize = 4;
pub const SIG_COEF_CONTEXTS_EOB: usize = 4;
pub const SIG_COEF_CONTEXTS_2D: usize = 26;
pub const SIG_COEF_CONTEXTS: usize = 42;
pub const SIG_REF_DIFF_OFFSET_NUM: usize = 5;
pub const SUPERRES_NUM: usize = 8;
pub const SUPERRES_DENOM_MIN: usize = 9;
pub const SUPERRES_DENOM_BITS: usize = 3;
pub const SUPERRES_FILTER_BITS: usize = 6;
pub const SUPERRES_FILTER_SHIFTS: usize = 1<<SUPERRES_FILTER_BITS;
pub const SUPERRES_FILTER_TAPS: usize = 8;
pub const SUPERRES_FILTER_OFFSET: usize = 3;
pub const SUPERRES_SCALE_BITS: usize = 14;
pub const SUPERRES_SCALE_MASK: usize = (1<<14) - 1;
pub const SUPERRES_EXTRA_BITS: usize = 8;
pub const TXB_SKIP_CONTEXTS: usize = 13;
pub const EOB_COEF_CONTEXTS: usize = 22;
pub const DC_SIGN_CONTEXTS: usize = 3;
pub const LEVEL_CONTEXTS: usize = 21;
pub const TX_CLASS_2D: usize = 0;
pub const TX_CLASS_HORIZ: usize = 1;
pub const TX_CLASS_VERT: usize = 2;
pub const REFMVS_LIMIT: usize = (1<<12) - 1;
pub const INTRA_FILTER_SCALE_BITS: usize = 4;
pub const INTRA_FILTER_MODES: usize = 5;
pub const COEFF_CDF_Q_CTXS: usize = 4;
pub const PRIMARY_REF_NONE: usize = 7;